### ISSUE TITLE
eatonBlue[500] !== Eaton's Blue

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-colors#43]
![image](https://user-images.githubusercontent.com/8997218/150621109-a221d4e3-eb59-4e68-9166-3af471362f46.png)

#### Describe the bug

eatonBlue500 === `#005EAB`

#### What is the expected behavior?

Eaton's Blue, according to Eaton.com, is `#005EB8`
		
#### Anything else to add?

Discovered during A11y research

**Comment by emclaug2** [comment]
This sounds like it'll be grouped into the a11y refactor discussions we have scheduled.

**Comment by huayunh** [comment]
no it is unrelated. EatonBlue is a branding color.

**Comment by emclaug2** [comment]
Whenever you say it's a branding color, would this mean our branding palette would have be updated?

**Comment by huayunh** [comment]
Correct. It belongs to the colors-branding package. Our accessibility discussion only deals with the colors package.

**Comment by huayunh** [comment]
Unless we ended up making "Eaton's blue" to be our new blue500... Can do, although not my favorite.

**Comment by huayunh** [comment]
Will be fixed with the new colors package / theme
